name: CloudStream Derleyici

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"

permissions:
  contents: write

jobs:
  CloudStreamDerleyici:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Kontrol Et
        uses: actions/checkout@v4
        with:
          ref: master

      - name: JDK 17 Ayarla
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Çıktı Klasörünü Hazırla
        run: mkdir -p builds

      - name: Eklentileri Derle
        run: gradle make

      - name: Derlemeleri builds Dalına Yükle
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./builds
          publish_branch: builds
          force_orphan: true
